# https://aka.ms/yaml

trigger:
- main
- develop

pr:
- main
- develop

variables:
  DotNetVersion: 6.0.100-preview.3.21202.5
  DotNet.Cli.Telemetry.OptOut: true
  Android.Msi: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4624420/6.0.1xx-preview3/7d6cd1cde4182d7db2cfc5d0b55364c972b6d34f/Microsoft.NET.Workload.Android.11.0.200.196.msi
  Android.Pkg: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4624420/6.0.1xx-preview3/7d6cd1cde4182d7db2cfc5d0b55364c972b6d34f/Microsoft.NET.Workload.Android-11.0.200-preview.3.196.pkg
  iOS.Msi: https://bosstoragemirror.azureedge.net/wrench/6.0.1xx-preview3/f68d4d9c2a342daf9eaad364ccbe252e009d3901/4623693/package/Microsoft.NET.Workload.iOS.14.4.100-preview.3.1326.msi
  iOS.Pkg: https://bosstoragemirror.azureedge.net/wrench/6.0.1xx-preview3/f68d4d9c2a342daf9eaad364ccbe252e009d3901/4623693/package/notarized/Microsoft.iOS.Bundle.14.4.100-preview.3.1326.pkg
  macOS.Pkg: https://bosstoragemirror.azureedge.net/wrench/6.0.1xx-preview3/f68d4d9c2a342daf9eaad364ccbe252e009d3901/4623693/package/notarized/Microsoft.macOS.Bundle.11.1.100-preview.3.1379.pkg
  MacCatalyst.Pkg: https://bosstoragemirror.azureedge.net/wrench/6.0.1xx-preview3/f68d4d9c2a342daf9eaad364ccbe252e009d3901/4623693/package/notarized/Microsoft.MacCatalyst.Bundle.14.3.100-preview.3.471.pkg

jobs:
- job: windows
  pool:
    vmImage: windows-latest
  variables:
    LogDirectory: $(Build.ArtifactStagingDirectory)\logs
  steps:
    - powershell: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        & .\dotnet-install.ps1 -Version $(DotNetVersion) -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        & dotnet --list-sdks
      displayName: install .NET $(DotNetVersion)
      errorActionPreference: stop

    - powershell: |
        & dotnet tool install --global boots
        & boots $(Android.Msi)
        & boots $(iOS.Msi)
      displayName: install .NET workloads
      errorActionPreference: stop

    - powershell: |
        & dotnet build net6-samples.sln -c Debug   -bl:$(LogDirectory)\Debug.binlog
        & dotnet build net6-samples.sln -c Release -bl:$(LogDirectory)\Release.binlog
      displayName: build samples
      errorActionPreference: stop

    - task: MSBuild@1
      displayName: build WinUI3 Debug
      inputs:
        solution: HelloWinUI3/HelloWinUI3.sln
        msbuildArguments: -restore -p:Configuration=Debug -bl:$(LogDirectory)\WinUI3-Debug.binlog

    - task: MSBuild@1
      displayName: build WinUI3 Release
      inputs:
        solution: HelloWinUI3/HelloWinUI3.sln
        msbuildArguments: -p:Configuration=Release -bl:$(LogDirectory)\WinUI3-Release.binlog

    - task: CopyFiles@2
      displayName: copy artifacts
      inputs:
        contents: '*Android\**\*-Signed.apk'
        targetFolder: $(Build.ArtifactStagingDirectory)
        overWrite: true
      condition: always()

    - task: PublishPipelineArtifact@1
      displayName: publish artifacts
      inputs:
        artifactName: windows-artifacts
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()

- job: mac
  timeoutInMinutes: 120
  pool:
    vmImage: macOS-latest
  variables:
    - name: LogDirectory
      value: $(Build.ArtifactStagingDirectory)/logs
    - name: DotNet.Root
      value: /usr/local/share/dotnet/
    - name: DotNet.Tools
      value: ~/.dotnet/tools
  steps:
    - task: UseDotNet@2
      displayName: install .NET Core 3.1
      inputs:
        version: 3.1.x
        installationPath: $(DotNet.Root)

    - bash: >
        export PATH="$(DotNet.Root):$(DotNet.Tools):$PATH" &&
        curl -L https://raw.githubusercontent.com/dotnet/install-scripts/7a9d5dcab92cf131fc2d8977052f8c2c2d540e22/src/dotnet-install.sh > dotnet-install.sh &&
        sh dotnet-install.sh --version $(DotNetVersion) --install-dir $DOTNET_ROOT --verbose &&
        dotnet --list-sdks &&
        echo "##vso[task.setvariable variable=PATH]$PATH"
      displayName: install .NET $(DotNetVersion)

    - bash: |
        dotnet tool install --global boots
        boots $(Android.Pkg)
        boots $(iOS.Pkg)
        boots $(macOS.Pkg)
        boots $(MacCatalyst.Pkg)
      displayName: install .NET workloads

    - bash: sudo xcode-select -s /Applications/Xcode_12.4.app
      displayName: select Xcode 12.4

    - bash: |
        set -x
        mkdir -p ~/Library/Preferences/Xamarin
        rm -f ~/Library/Preferences/Xamarin/Settings.plist
        /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist || true
        cat ~/Library/Preferences/Xamarin/Settings.plist || true
      displayName: configure vsmac xcode

    - bash: |
        dotnet build net6-samples.sln -c Debug   -bl:$(LogDirectory)/Debug.binlog &&
        dotnet build net6-samples.sln -c Release -bl:$(LogDirectory)/Release.binlog
      displayName: build samples

    - bash: |
        dotnet build vs/net6-samples-mac.sln -c Debug   -bl:$(LogDirectory)/Debug-Mac.binlog &&
        dotnet build vs/net6-samples-mac.sln -c Release -bl:$(LogDirectory)/Release-Mac.binlog
      displayName: build macOS-only samples

    - task: CopyFiles@2
      displayName: copy artifacts
      inputs:
        contents: |
          *Android/**/*-Signed.apk
          *iOS/**/*.app/**
          *Mac*/**/*.app/**
        targetFolder: $(Build.ArtifactStagingDirectory)
        overWrite: true
      condition: always()

    - task: PublishPipelineArtifact@1
      displayName: publish artifacts
      inputs:
        artifactName: mac-artifacts
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()
